### ISSUE TITLE
Use for month to month

### ISSUE THREAD

**Issue by bishopgodsey** [EWliturgy/CatholicLiturgicalCalendar#1]
Is it possible to have this display only the current month's calendar? Like a website set up to hold just the current month's calendar. If so, how?

**Comment by EWliturgy** [comment]
You can choose a the desired month of the year from near the top of the screen. Is that what you want? Or do you wish to run this calendar somewhere, and link only to the current month?

On 19/03/16 07:48, Bishop Gregory Godsey wrote:

Is it possible to have this display only the current month's calendar? Like a website set up to hold just the current month's calendar. If so, how?

**Comment by EWliturgy** [comment]
If you are asking if a direct URL can be used to point to a single, given month, then no. A simple, intermediate page could be written to do this, and you could link to that. But as it stands now, the calendar presents the month of January first.
